language: julia
codecov: true
coveralls: true
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
    - nightly
sudo: false
matrix:
    allow_failures:
        - julia: nightly
    fast_finish: true
script:
    - julia -e 'using Pkg; Pkg.add("Coverage")'
    - julia -e 'using Pkg; Pkg.test("Input", coverage=true)'
notifications:
    email: false
after_success:
    - julia -e 'using Coverage; Codecov.submit(process_folder())'
    - julia -e 'using Coverage; Coveralls.submit(process_folder())'
